### ISSUE TITLE
Error: EPERM: operation not permitted, scandir '/Users/yws/.Trash'

### ISSUE THREAD

**Issue by yinwangsong** [slidevjs/themes#11] opened 2022-09-10 13:56 UTC
'''
(base) yws@ywsdeMacBook-Pro ~ % sudo slidev
Password:
✔ The theme "@slidev/theme-seriph" was not found globally, do you want to install it now? … yes

added 5 packages in 3s
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EPERM: operation not permitted, scandir '/Users/yws/.Trash'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/yws/.Trash'
}
'''

When I installed slidev globally , it forced me to install the theme , after i installed it using sudo , a bug happen.

**Comment by antfu** [comment] 2022-09-19 02:38
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2022-09-19 02:38 UTC
